// PatentPriorArtTab — Search and manage prior art references

import { useState } from 'react'
import { Search, Loader2, AlertTriangle, ExternalLink, Trash2 } from 'lucide-react'
import { supabase } from '../../../lib/supabase'

export default function PatentPriorArtTab({ application, onReload }) {
  const [searching, setSearching] = useState(false)
  const [error, setError] = useState(null)

  const priorArt = application.priorArt || []

  const handleSearch = async () => {
    setSearching(true)
    setError(null)
    try {
      const claimsText = (application.claims || []).map(c => c.claim_text).join('\n')
      const res = await fetch('/.netlify/functions/patent-prior-art', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: application.title,
          description: application.detailed_description || application.specification,
          claims: claimsText,
        }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Search failed')

      // Save results to Supabase
      if (data.results?.length) {
        for (const result of data.results) {
          await supabase.from('patent_prior_art_results').insert({
            application_id: application.id,
            patent_number: result.patent_number,
            title: result.title,
            abstract: result.abstract,
            relevance_score: result.relevance_score,
            similarity_explanation: result.similarity_explanation,
            is_blocking: result.is_blocking || false,
            source: result.source || 'ai_simulated',
          })
        }
        onReload()
      }
    } catch (err) {
      console.error('Prior art search failed:', err)
      setError(err.message)
    } finally {
      setSearching(false)
    }
  }

  const handleDelete = async (resultId) => {
    await supabase.from('patent_prior_art_results').delete().eq('id', resultId)
    onReload()
  }

  return (
    <div className="p-6 max-w-4xl space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-base font-semibold text-ink">Prior Art</h2>
          <p className="text-xs text-ink-muted mt-0.5">{priorArt.length} references found</p>
        </div>
        <button
          onClick={handleSearch}
          disabled={searching}
          className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 text-white text-xs font-medium rounded-lg hover:bg-blue-700 disabled:opacity-50"
        >
          {searching ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Search className="w-3.5 h-3.5" />}
          Search Prior Art
        </button>
      </div>

      {/* AI Simulation Warning */}
      <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 flex items-start gap-2">
        <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
        <div className="text-xs text-amber-700">
          <strong>AI-simulated results.</strong> These references are generated by AI for planning purposes.
          Always verify with actual USPTO searches at{' '}
          <a href="https://ppubs.uspto.gov/pubwebapp/" target="_blank" rel="noopener noreferrer" className="underline">
            USPTO Patent Public Search
          </a>.
        </div>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-3 text-xs text-red-700">{error}</div>
      )}

      {priorArt.length === 0 ? (
        <div className="bg-white rounded-xl border border-rule p-8 text-center">
          <p className="text-sm text-ink-muted">No prior art references yet. Click "Search Prior Art" to find relevant patents.</p>
        </div>
      ) : (
        <div className="space-y-3">
          {priorArt.map(ref => (
            <div key={ref.id} className={`bg-white rounded-lg border ${ref.is_blocking ? 'border-red-300' : 'border-rule'} p-4`}>
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    {ref.patent_number && (
                      <span className="text-xs font-mono font-bold text-blue-700">{ref.patent_number}</span>
                    )}
                    {ref.is_blocking && (
                      <span className="px-1.5 py-0.5 text-[10px] font-medium bg-red-100 text-red-700 rounded">BLOCKING</span>
                    )}
                    {ref.relevance_score != null && (
                      <span className={`px-1.5 py-0.5 text-[10px] font-medium rounded ${
                        ref.relevance_score >= 70 ? 'bg-red-100 text-red-700' :
                        ref.relevance_score >= 40 ? 'bg-amber-100 text-amber-700' :
                        'bg-green-100 text-green-700'
                      }`}>
                        {ref.relevance_score}% relevance
                      </span>
                    )}
                  </div>
                  <h4 className="text-sm font-medium text-ink">{ref.title}</h4>
                  {ref.abstract && <p className="text-xs text-ink-muted mt-1 line-clamp-2">{ref.abstract}</p>}
                  {ref.similarity_explanation && (
                    <p className="text-xs text-ink mt-2 bg-gray-50 rounded p-2">{ref.similarity_explanation}</p>
                  )}
                </div>
                <button onClick={() => handleDelete(ref.id)} className="p-1 text-red-400 hover:text-red-600 shrink-0">
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
